apiVersion: v1
kind: Pod
metadata:
  name: node.kops.thnks.tk
  labels:
    app: nodejs-hello-world
spec:
  containers:
  - name: nodejs-hello-world
    image: deploymentking/kops-node-app
    ports:
    - name: nodejs-port
      containerPort: 3000