apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-service
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: nodejs-hello-world
  type: LoadBalancer
