apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-hello-world-dep
  template:
    metadata:
      labels:
        app: nodejs-hello-world-dep
    spec:
      containers:
      - name: nodejs-hello-world
        image: deploymentking/kops-node-app
        ports:
        - name: nodejs-port
          containerPort: 3000