apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-world-deployment
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nodejs.kops.thnks.tk.
  labels:
    app: nodejs.kops.thnks.tk
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: nodejs-hello-world-dep
